name: SurvivalPlus
author: HawkeyNL
version: 0.0.1
description: This plugins adds extra fun stuff to a unique survival world.
main: me.hawkeynl.survivalplus.SurvivalPlus
api-version: 1.16
commands:
  enchants:
  repair:
  enderchest:
    aliases:
      - echest
  craft:
  tpa:
  tpaccept:
    aliases:
      - tpac
      - accept
  tpdeny:
    aliases:
      - deny
